version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=firedepartmentmanager
      - POSTGRES_PASSWORD=firedepartmentmanager
      - POSTGRES_DB=firedepartmentmanager
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
