# Generated by Django 3.2 on 2021-04-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strazacy',
            name='termin_kpp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
