# Generated by Django 3.1.3 on 2021-05-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_strazacy_termin_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strazacy',
            name='kierowca',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='strazacy',
            name='termin_prawa_jazdy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strazacy',
            name='termin_wkladki',
            field=models.DateField(blank=True, null=True),
        ),
    ]
