# Generated by Django 3.2 on 2021-05-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_uwagapojazdy_uwagasprzet_uwagastrazacy_uwagauslugi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uwagapojazdy',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'DONE'), (3, 'REJECTED')], default=1),
        ),
        migrations.AlterField(
            model_name='uwagasprzet',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'DONE'), (3, 'REJECTED')], default=1),
        ),
        migrations.AlterField(
            model_name='uwagastrazacy',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'DONE'), (3, 'REJECTED')], default=1),
        ),
        migrations.AlterField(
            model_name='uwagauslugi',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'DONE'), (3, 'REJECTED')], default=1),
        ),
    ]
