# Generated by Django 3.2 on 2021-05-31 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0005_merge_0003_auto_20210528_1739_0004_auto_20210516_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='UwagaPrzegladSprzet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'DONE'), (3, 'REJECTED')], default=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.przegladsprzet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UwagaPrzegladPojazdy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'DONE'), (3, 'REJECTED')], default=1)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.przegladpojazdy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
